module.exports = {
  string: "string",
  number: "number",
  object: "object",
  stringArray: ["string"],
  numberArray: ["number"],
  any: "any",
  array: [],
  objectArray: ["object"],
  optional: "?",
  oneOf: "%",
  null: null,
  asOneOf: key => key + "%",
  asOptional: key => key + "?",
};
